version: "3.8"

services:
  airflow:
    working_dir: /opt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./airflow
        target: /opt/airflow
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:${AIRFLOW_DOCKER_PASSWORD}@metadb:5432/airflow